export const storeProducts = [
    {
      id: 1,
      title: "Google Pixel 3a",
      img: "img/product-1.png",
      price: 10,
      company: "Google",
      color: ["Black","Blue","Grey"],
      colorType:["#000000","#0B1888","#78797E"],
      memory:["16GB","32GB","64GB"],
      images:["img/google/camera.jpg","img/google/battery.jpg","img/google/processor.jpg"],
      thumb:["img/google/thumb1.jpg","img/google/thumb2.jpg","img/google/thumb3.jpg","img/google/thumb4.jpg"],
      thumb_target:["img/google/img-target1.jpg","img/google/img-target2.jpg","img/google/img-target3.jpg","img/google/img-target4.jpg"],
      battery:"Get more done with an Adaptive Battery that delivers 7 hours of use on just a 15-minute charge. It’s designed to learn your favorite apps and reduce power to the ones you rarely use.",
      camera:"Take flawless photos with Portrait Mode. Capture beautiful portraits that focus on your subject as the background fades into a blur. Free, unlimited storage with Google Photos.² Save all your photos and videos with free, unlimited storage at high quality with Google Photos. Keep everyone in focus. Motion Auto Focus will make sure the people and pets in your shot stay sharp as you snap away.",
      processor:"3 years of security and OS updates. Keep your phone protected against the latest threats and performing at its best.5 Keep your data protected. The custom-made Titan M security chip helps secure the operating system and your most sensitive data, like passwords.6 Keep more of what you love. Use the Quick Switch Adapter to transfer your messages, contacts and photos to your new device.",
      inCart: false,
      inWishlist:false,
      count: 0,
      total: 0,
      specification:{
        brand:"Google",
        model:"Google Pixel 3a",
        camera:"12.2MP primary camera and 8MP front facing camera",
        battery:"3520mAH lithium-ion battery",
        processor:"Snapdragon 835 64-bit octa core processor",
        os:"Android v8.0.1 Oreo operating system",
        sf:"Single SIM, Music Player, Video Player, E-mail"
      },
    },
    {
      id: 2,
      title: "Samsung Galaxy M30",
      img: "img/product-2.png",
      price: 16,
      company: "Samsung",
      color: ["Black","Blue","Silver"],
      colorType:["#000000","#0B1888","#d9d9d9"],
      memory:["16GB","32GB","64GB"],
      images:["img/samsung/camera.jpg","img/samsung/battery.jpg","img/samsung/processor.jpg"],
      thumb:["img/samsung/m30/thumb1.jpg","img/samsung/m30/thumb2.jpg","img/samsung/m30/thumb3.jpg","img/samsung/m30/thumb4.jpg"],
      thumb_target:["img/samsung/m30/img-target1.jpg","img/samsung/m30/img-target2.jpg","img/samsung/m30/img-target3.jpg","img/samsung/m30/img-target4.jpg"],
      battery:"Get more done with an Adaptive Battery that delivers 7 hours of use on just a 15-minute charge. It’s designed to learn your favorite apps and reduce power to the ones you rarely use.",
      camera:"Take flawless photos with Portrait Mode. Capture beautiful portraits that focus on your subject as the background fades into a blur. Free, unlimited storage with Google Photos.² Save all your photos and videos with free, unlimited storage at high quality with Google Photos. Keep everyone in focus. Motion Auto Focus will make sure the people and pets in your shot stay sharp as you snap away.",
      processor:"3 years of security and OS updates. Keep your phone protected against the latest threats and performing at its best.5 Keep your data protected. The custom-made Titan M security chip helps secure the operating system and your most sensitive data, like passwords.6 Keep more of what you love. Use the Quick Switch Adapter to transfer your messages, contacts and photos to your new device.",
      inCart: false,
      inWishlist:false,
      count: 0,
      total: 0,
      specification:{
        brand:"Samsung",
        model:"Samsung Galaxy M30",
        camera:"13+5+5MP Triple rear camera with f1.9 aperture, 2.2 wide angle, 2.2 flash | 16MP front camera with f2.0 aperture",
        battery:"5000mAH lithium-ion battery with 3x fast charge | 15W Type-C fast charger in the box",
        processor:"1.8GHz Exynos 7904 octa core processor",
        os:"Android Oreo v8.1 operating system with 1.8GHz",
        sf:"Dual SIM (nano+nano) dual-standby (4G+4G), USB Version: USB 2.0 ; Color Depth (Main Display): 16M ; Bluetooth: v5.0"
      },
    },
    {
      id: 3,
      title: "HTC Desire 620G",
      img: "img/product-3.png",
      price: 8,
      company: "HTC",
      color: ["Black","Blue","Silver"],
        colorType:["#000000","#0B1888","#d9d9d9"],
        memory:["16GB","32GB","64GB"],
        images:["img/htc/camera.jpg","img/htc/battery.jpg","img/htc/processor.jpg"],
        thumb:["img/htc/620g/thumb1.jpg","img/htc/620g/thumb2.jpg","img/htc/620g/thumb3.jpg","img/htc/620g/thumb4.jpg"],
        thumb_target:["img/htc/620g/img-target1.jpg","img/htc/620g/img-target2.jpg","img/htc/620g/img-target3.jpg","img/htc/620g/img-target4.jpg"],
        battery:"Get more done with an Adaptive Battery that delivers 7 hours of use on just a 15-minute charge. It’s designed to learn your favorite apps and reduce power to the ones you rarely use.",
        camera:"Take flawless photos with Portrait Mode. Capture beautiful portraits that focus on your subject as the background fades into a blur. Free, unlimited storage with Google Photos.² Save all your photos and videos with free, unlimited storage at high quality with Google Photos. Keep everyone in focus. Motion Auto Focus will make sure the people and pets in your shot stay sharp as you snap away.",
        processor:"3 years of security and OS updates. Keep your phone protected against the latest threats and performing at its best.5 Keep your data protected. The custom-made Titan M security chip helps secure the operating system and your most sensitive data, like passwords.6 Keep more of what you love. Use the Quick Switch Adapter to transfer your messages, contacts and photos to your new device.",
        inCart: false,
        inWishlist:false,
        count: 0,
        total: 0,
        specification:{
          brand:"HTC",
          model:"HTC Desire 620G",
          camera:"13MP primary camera with auto focus, BSI sensor, 1080p video recording and 8MP front facing camera",
          battery:"2600mAH lithium-ion battery",
          processor:"1.7GHz MT6592 octa core processor",
          os:"Android v4.4 KitKat operating system",
          sf:"1GB RAM, 16GB internal memory expandable up to 32GB and dual nano SIM (GSM+GSM),Accelerometer; Photo/video editor; proximity; compass",
        },
    },
    {
      id: 4,
      title: "HTC Desire 728G",
      img: "img/product-4.png",
      price: 18,
      company: "HTC",
      color: ["Black","Blue","White"],
      colorType:["#000000","#0B1888","#ffffff"],
      memory:["16GB","32GB","64GB"],
      images:["img/htc/camera.jpg","img/htc/battery.jpg","img/htc/processor.jpg"],
      thumb:["img/htc/728g/thumb1.jpg","img/htc/728g/thumb2.jpg","img/htc/728g/thumb3.jpg","img/htc/728g/thumb4.jpg"],
      thumb_target:["img/htc/728g/img-target1.jpg","img/htc/728g/img-target2.jpg","img/htc/728g/img-target3.jpg","img/htc/728g/img-target4.jpg"],
      battery:"Get more done with an Adaptive Battery that delivers 7 hours of use on just a 15-minute charge. It’s designed to learn your favorite apps and reduce power to the ones you rarely use.",
      camera:"Take flawless photos with Portrait Mode. Capture beautiful portraits that focus on your subject as the background fades into a blur. Free, unlimited storage with Google Photos.² Save all your photos and videos with free, unlimited storage at high quality with Google Photos. Keep everyone in focus. Motion Auto Focus will make sure the people and pets in your shot stay sharp as you snap away.",
      processor:"3 years of security and OS updates. Keep your phone protected against the latest threats and performing at its best.5 Keep your data protected. The custom-made Titan M security chip helps secure the operating system and your most sensitive data, like passwords.6 Keep more of what you love. Use the Quick Switch Adapter to transfer your messages, contacts and photos to your new device.",
      inCart: false,
      inWishlist:false,
      count: 0,
      total: 0,
      specification:{
        brand:"HTC",
        model:"HTC Desire 728G",
        camera:"13MP primary camera with auto focus, BSI sensor, 1080p video recording and 8MP front facing camera",
        battery:"2600mAH lithium-ion battery",
        processor:"1.7GHz MT6592 octa core processor",
        os:"Android v4.4 KitKat operating system",
        sf:"1GB RAM, 16GB internal memory expandable up to 32GB and dual nano SIM (GSM+GSM),Accelerometer; Photo/video editor; proximity; compass",
      },
    },
    {
      id: 5,
      title: "HTC Desire 626s",
      img: "img/product-5.png",
      price: 24,
      company: "HTC",
      color: ["Black","Blue","Silver"],
      colorType:["#000000","#0B1888","#d9d9d9"],
      memory:["16GB","32GB","64GB"],
      images:["img/htc/camera.jpg","img/htc/battery.jpg","img/htc/processor.jpg"],
      thumb:["img/htc/626s/thumb1.jpg"],
      thumb_target:["img/htc/626s/img-target1.jpg"],
      battery:"Get more done with an Adaptive Battery that delivers 7 hours of use on just a 15-minute charge. It’s designed to learn your favorite apps and reduce power to the ones you rarely use.",
      camera:"Take flawless photos with Portrait Mode. Capture beautiful portraits that focus on your subject as the background fades into a blur. Free, unlimited storage with Google Photos.² Save all your photos and videos with free, unlimited storage at high quality with Google Photos. Keep everyone in focus. Motion Auto Focus will make sure the people and pets in your shot stay sharp as you snap away.",
      processor:"3 years of security and OS updates. Keep your phone protected against the latest threats and performing at its best.5 Keep your data protected. The custom-made Titan M security chip helps secure the operating system and your most sensitive data, like passwords.6 Keep more of what you love. Use the Quick Switch Adapter to transfer your messages, contacts and photos to your new device.",
      inCart: false,
      inWishlist:false,
      count: 0,
      total: 0,
      specification:{
        brand:"HTC",
        model:"HTC Desire 626s",
        camera:"13MP primary camera with auto focus, BSI sensor, 1080p video recording and 8MP front facing camera",
        battery:"2600mAH lithium-ion battery",
        processor:"1.7GHz MT6592 octa core processor",
        os:"Android v4.4 KitKat operating system",
        sf:"1GB RAM, 16GB internal memory expandable up to 32GB and dual nano SIM (GSM+GSM),Accelerometer; Photo/video editor; proximity; compass",
      },
    },
    {
      id: 6,
      title: "Apple Iphone Xs Max",
      img: "img/product-6.png",
      price: 17,
      company: "Apple",
      color: ["Black","Blue","White"],
      colorType:["#000000","#0B1888","#ffffff"],
      memory:["16GB","32GB","64GB"],
      images:["img/apple/camera.jpg","img/apple/battery.jpg","img/apple/processor.jpg"],
      thumb:["img/apple/xs-max/thumb1.jpg","img/apple/xs-max/thumb2.jpg","img/apple/xs-max/thumb3.jpg","img/apple/xs-max/thumb4.jpg"],
      thumb_target:["img/apple/xs-max/img-target1.jpg","img/apple/xs-max/img-target2.jpg","img/apple/xs-max/img-target3.jpg","img/apple/xs-max/img-target4.jpg"],
      battery:"Get more done with an Adaptive Battery that delivers 7 hours of use on just a 15-minute charge. It’s designed to learn your favorite apps and reduce power to the ones you rarely use.",
      camera:"Take flawless photos with Portrait Mode. Capture beautiful portraits that focus on your subject as the background fades into a blur. Free, unlimited storage with Google Photos.² Save all your photos and videos with free, unlimited storage at high quality with Google Photos. Keep everyone in focus. Motion Auto Focus will make sure the people and pets in your shot stay sharp as you snap away.",
      processor:"3 years of security and OS updates. Keep your phone protected against the latest threats and performing at its best.5 Keep your data protected. The custom-made Titan M security chip helps secure the operating system and your most sensitive data, like passwords.6 Keep more of what you love. Use the Quick Switch Adapter to transfer your messages, contacts and photos to your new device.",
      inCart: false,
      inWishlist:false,
      count: 0,
      total: 0,
      specification:{
        brand:"Apple",
        model:"Apple Iphone Xs Max",
        camera:"12MP dual cameras with dual OIS and 7MP TrueDepth front camera — Portrait mode, Portrait Lighting, Depth Control and Smart HDR",
        battery:"Talk time (wireless): Up to 20 hours, Internet use: Up to 12 hours, Video playback (wireless): Up to 14 hours",
        processor:"1.7GHz MT6592 octa core processor",
        os:"iOS 12 with Memoji, Screen Time, Siri Shortcuts, and Group FaceTime",
        sf:"Face ID for secure authentication3,IP68 dust and water resistant (maximum depth of 2 metres up to 30 minutes)2",
      },
    },
    {
      id: 7,
      title: "Iphone 8",
      img: "img/product-7.png",
      price: 30,
      company: "Apple",
      color: ["Black","Blue","White"],
      colorType:["#000000","#0B1888","#ffffff"],
      memory:["16GB","32GB","64GB"],
      images:["img/apple/camera.jpg","img/apple/battery.jpg","img/apple/processor.jpg"],
      thumb:["img/apple/i8/thumb1.jpg","img/apple/i8/thumb2.jpg","img/apple/i8/thumb3.jpg","img/apple/i8/thumb4.jpg"],
      thumb_target:["img/apple/i8/img-target1.jpg","img/apple/i8/img-target2.jpg","img/apple/i8/img-target3.jpg","img/apple/i8/img-target4.jpg"],
      battery:"Get more done with an Adaptive Battery that delivers 7 hours of use on just a 15-minute charge. It’s designed to learn your favorite apps and reduce power to the ones you rarely use.",
      camera:"Take flawless photos with Portrait Mode. Capture beautiful portraits that focus on your subject as the background fades into a blur. Free, unlimited storage with Google Photos.² Save all your photos and videos with free, unlimited storage at high quality with Google Photos. Keep everyone in focus. Motion Auto Focus will make sure the people and pets in your shot stay sharp as you snap away.",
      processor:"3 years of security and OS updates. Keep your phone protected against the latest threats and performing at its best.5 Keep your data protected. The custom-made Titan M security chip helps secure the operating system and your most sensitive data, like passwords.6 Keep more of what you love. Use the Quick Switch Adapter to transfer your messages, contacts and photos to your new device.",
      inCart: false,
      inWishlist:false,
      count: 0,
      total: 0,
      specification:{
        brand:"Apple",
        model:"Apple Iphone 8",
        camera:"12MP dual cameras with dual OIS and 7MP TrueDepth front camera — Portrait mode, Portrait Lighting, Depth Control and Smart HDR",
        battery:"Talk time (wireless): Up to 20 hours, Internet use: Up to 12 hours, Video playback (wireless): Up to 14 hours",
        processor:"1.7GHz MT6592 octa core processor",
        os:"iOS 12 with Memoji, Screen Time, Siri Shortcuts, and Group FaceTime",
        sf:"Face ID for secure authentication3,IP68 dust and water resistant (maximum depth of 2 metres up to 30 minutes)2",
      },
    },
    {
      id: 8,
      title: "Apple Iphone Xs Max",
      img: "img/product-8.png",
      price: 18,
      company: "Apple",
      color: ["Black","Blue","White"],
      colorType:["#000000","#0B1888","#ffffff"],
      memory:["16GB","32GB","64GB"],
      images:["img/apple/camera.jpg","img/apple/battery.jpg","img/apple/processor.jpg"],
      thumb:["img/apple/max/thumb1.jpg","img/apple/max/thumb2.jpg","img/apple/max/thumb3.jpg","img/apple/max/thumb4.jpg"],
      thumb_target:["img/apple/max/img-target1.jpg","img/apple/max/img-target2.jpg","img/apple/max/img-target3.jpg","img/apple/max/img-target4.jpg"],
      battery:"Get more done with an Adaptive Battery that delivers 7 hours of use on just a 15-minute charge. It’s designed to learn your favorite apps and reduce power to the ones you rarely use.",
      camera:"Take flawless photos with Portrait Mode. Capture beautiful portraits that focus on your subject as the background fades into a blur. Free, unlimited storage with Google Photos.² Save all your photos and videos with free, unlimited storage at high quality with Google Photos. Keep everyone in focus. Motion Auto Focus will make sure the people and pets in your shot stay sharp as you snap away.",
      processor:"3 years of security and OS updates. Keep your phone protected against the latest threats and performing at its best.5 Keep your data protected. The custom-made Titan M security chip helps secure the operating system and your most sensitive data, like passwords.6 Keep more of what you love. Use the Quick Switch Adapter to transfer your messages, contacts and photos to your new device.",
      inCart: false,
      inWishlist:false,
      count: 0,
      total: 0,
      specification:{
        brand:"Apple",
        model:"Apple Iphone Xs Max",
        camera:"12MP dual cameras with dual OIS and 7MP TrueDepth front camera — Portrait mode, Portrait Lighting, Depth Control and Smart HDR",
        battery:"Talk time (wireless): Up to 20 hours, Internet use: Up to 12 hours, Video playback (wireless): Up to 14 hours",
        processor:"1.7GHz MT6592 octa core processor",
        os:"iOS 12 with Memoji, Screen Time, Siri Shortcuts, and Group FaceTime",
        sf:"Face ID for secure authentication3,IP68 dust and water resistant (maximum depth of 2 metres up to 30 minutes)2",
      },
    },
    {
        id: 9,
        title: "OnePlus 6T",
        img: "img/huawei-1.jpg",
        price: 15,
        company: "OnePlus",
        color: ["Black","Blue","White"],
        colorType:["#000000","#0B1888","#ffffff"],
        memory:["16GB","32GB","64GB"],
        images:["img/oneplus/camera.jpg","img/oneplus/battery.jpg","img/oneplus/processor.jpg"],
        thumb:["img/oneplus/6t/thumb1.jpg","img/oneplus/6t/thumb2.jpg","img/oneplus/6t/thumb3.jpg","img/oneplus/6t/thumb4.jpg"],
        thumb_target:["img/oneplus/6t/img-target1.jpg","img/oneplus/6t/img-target2.jpg","img/oneplus/6t/img-target3.jpg","img/oneplus/6t/img-target4.jpg"],
        battery:"Get more done with an Adaptive Battery that delivers 7 hours of use on just a 15-minute charge. It’s designed to learn your favorite apps and reduce power to the ones you rarely use.",
        camera:"Take flawless photos with Portrait Mode. Capture beautiful portraits that focus on your subject as the background fades into a blur. Free, unlimited storage with Google Photos.² Save all your photos and videos with free, unlimited storage at high quality with Google Photos. Keep everyone in focus. Motion Auto Focus will make sure the people and pets in your shot stay sharp as you snap away.",
        processor:"3 years of security and OS updates. Keep your phone protected against the latest threats and performing at its best.5 Keep your data protected. The custom-made Titan M security chip helps secure the operating system and your most sensitive data, like passwords.6 Keep more of what you love. Use the Quick Switch Adapter to transfer your messages, contacts and photos to your new device.",
        inCart: false,
        inWishlist:false,
        count: 0,
        total: 0,
        specification:{
          brand:"OnePlus",
          model:"OnePlus 6T",
          camera:"12MP dual cameras with dual OIS and 7MP TrueDepth front camera — Portrait mode, Portrait Lighting, Depth Control and Smart HDR",
          battery:"Talk time (wireless): Up to 20 hours, Internet use: Up to 12 hours, Video playback (wireless): Up to 14 hours",
          processor:"1.7GHz MT6592 octa core processor",
          os:"iOS 12 with Memoji, Screen Time, Siri Shortcuts, and Group FaceTime",
          sf:"Face ID for secure authentication3,IP68 dust and water resistant (maximum depth of 2 metres up to 30 minutes)2",
        },
      },
      {
        id: 10,
        title: "Redmi Note 6",
        img: "img/redmi-2.png",
        price: 2.5,
        company: "Xiaomi",
        color: ["Red","OceanBlue","Gold"],
        colorType:["#ff0000","#66ccff","#e6ac00"],
        memory:["16GB","32GB","64GB"],
        images:["img/xiaomi/camera.jpg","img/xiaomi/battery.jpg","img/xiaomi/processor.jpg"],
        thumb:["img/xiaomi/note6/thumb1.jpg","img/xiaomi/note6/thumb2.jpg","img/xiaomi/note6/thumb3.jpg","img/xiaomi/note6/thumb4.jpg"],
        thumb_target:["img/xiaomi/note6/img-target1.jpg","img/xiaomi/note6/img-target2.jpg","img/xiaomi/note6/img-target3.jpg","img/xiaomi/note6/img-target4.jpg"],
        battery:"Get more done with an Adaptive Battery that delivers 7 hours of use on just a 15-minute charge. It’s designed to learn your favorite apps and reduce power to the ones you rarely use.",
        camera:"Take flawless photos with Portrait Mode. Capture beautiful portraits that focus on your subject as the background fades into a blur. Free, unlimited storage with Google Photos.² Save all your photos and videos with free, unlimited storage at high quality with Google Photos. Keep everyone in focus. Motion Auto Focus will make sure the people and pets in your shot stay sharp as you snap away.",
        processor:"3 years of security and OS updates. Keep your phone protected against the latest threats and performing at its best.5 Keep your data protected. The custom-made Titan M security chip helps secure the operating system and your most sensitive data, like passwords.6 Keep more of what you love. Use the Quick Switch Adapter to transfer your messages, contacts and photos to your new device.",
        inCart: false,
        inWishlist:false,
        count: 0,
        total: 0,
        specification:{
          brand:"Xiaomi",
          model:"Xiaomi Note 6",
          camera:"12MP+5MP dual rear camera | 20MP+2MP dual front camera",
          battery:"4000mAH lithium-ion battery",
          processor:"1.8GHz Qualcomm Snapdragon 636 processor, Adreno 509",
          os:"Annote6 Oreo v8.1 operating system ",
          sf:"4GB RAM | 64GB internal memory expandable up to 256GB | Dual SIM (micro+nano) dual-standby (4G+4G)",
        },
      },
      {
        id: 11,
        title: "Redmi Mi Note 6 Pro",
        img: "img/nokia-1.jpg",
        price: 2.5,
        company: "Xiaomi",
        color: ["Red","OceanBlue","Gold"],
        colorType:["#ff0000","#66ccff","#e6ac00"],
        memory:["16GB","32GB","64GB"],
        images:["img/xiaomi/camera.jpg","img/xiaomi/battery.jpg","img/xiaomi/processor.jpg"],
        thumb:["img/xiaomi/6pro/thumb1.jpg","img/xiaomi/6pro/thumb2.jpg","img/xiaomi/6pro/thumb3.jpg","img/xiaomi/6pro/thumb4.jpg"],
        thumb_target:["img/xiaomi/6pro/img-target1.jpg","img/xiaomi/6pro/img-target2.jpg","img/xiaomi/6pro/img-target3.jpg","img/xiaomi/6pro/img-target4.jpg"],
        battery:"Get more done with an Adaptive Battery that delivers 7 hours of use on just a 15-minute charge. It’s designed to learn your favorite apps and reduce power to the ones you rarely use.",
        camera:"Take flawless photos with Portrait Mode. Capture beautiful portraits that focus on your subject as the background fades into a blur. Free, unlimited storage with Google Photos.² Save all your photos and videos with free, unlimited storage at high quality with Google Photos. Keep everyone in focus. Motion Auto Focus will make sure the people and pets in your shot stay sharp as you snap away.",
        processor:"3 years of security and OS updates. Keep your phone protected against the latest threats and performing at its best.5 Keep your data protected. The custom-made Titan M security chip helps secure the operating system and your most sensitive data, like passwords.6 Keep more of what you love. Use the Quick Switch Adapter to transfer your messages, contacts and photos to your new device.",
        inCart: false,
        inWishlist:false,
        count: 0,
        total: 0,
        specification:{
          brand:"Xiaomi",
          model:"Xiaomi Note 6 Pro",
          camera:"12MP+5MP dual rear camera | 20MP+2MP dual front camera",
          battery:"4000mAH lithium-ion battery",
          processor:"1.8GHz Qualcomm Snapdragon 636 processor, Adreno 509",
          os:"Android Oreo v8.1 operating system ",
          sf:"4GB RAM | 64GB internal memory expandable up to 256GB | Dual SIM (micro+nano) dual-standby (4G+4G)",
        },
      },
      {
        id: 12,
        title: "OnePlus 7 Plus",
        img: "img/oneplus-2.jpg",
        price: 2.6,
        company: "OnePlus",
        color: ["Black","Blue","White"],
        colorType:["#000000","#0B1888","#ffffff"],
        memory:["16GB","32GB","64GB"],
        images:["img/oneplus/camera.jpg","img/oneplus/battery.jpg","img/oneplus/processor.jpg"],
        thumb:["img/oneplus/6t/thumb1.jpg","img/oneplus/6t/thumb2.jpg","img/oneplus/6t/thumb3.jpg","img/oneplus/6t/thumb4.jpg"],
        thumb_target:["img/oneplus/6t/img-target1.jpg","img/oneplus/6t/img-target2.jpg","img/oneplus/6t/img-target3.jpg","img/aoneplus/6t/img-target4.jpg"],
        battery:"Get more done with an Adaptive Battery that delivers 7 hours of use on just a 15-minute charge. It’s designed to learn your favorite apps and reduce power to the ones you rarely use.",
        camera:"Take flawless photos with Portrait Mode. Capture beautiful portraits that focus on your subject as the background fades into a blur. Free, unlimited storage with Google Photos.² Save all your photos and videos with free, unlimited storage at high quality with Google Photos. Keep everyone in focus. Motion Auto Focus will make sure the people and pets in your shot stay sharp as you snap away.",
        processor:"3 years of security and OS updates. Keep your phone protected against the latest threats and performing at its best.5 Keep your data protected. The custom-made Titan M security chip helps secure the operating system and your most sensitive data, like passwords.6 Keep more of what you love. Use the Quick Switch Adapter to transfer your messages, contacts and photos to your new device.",
        inCart: false,
        inWishlist:false,
        count: 0,
        total: 0,
        specification:{
          brand:"OnePlus",
          model:"OnePlus 7 Plus",
          camera:"12MP dual cameras with dual OIS and 7MP TrueDepth front camera — Portrait mode, Portrait Lighting, Depth Control and Smart HDR",
          battery:"Talk time (wireless): Up to 20 hours, Internet use: Up to 12 hours, Video playback (wireless): Up to 14 hours",
          processor:"1.7GHz MT6592 octa core processor",
          os:"iOS 12 with Memoji, Screen Time, Siri Shortcuts, and Group FaceTime",
          sf:"Face ID for secure authentication3,IP68 dust and water resistant (maximum depth of 2 metres up to 30 minutes)2",
        },
      },
      {
        id: 13,
        title: "Honor 9lite",
        img: "img/huawei-3.png",
        price: 2.5,
        company: "Huawei",
        color: ["Black","Blue"],
        colorType:["#000000","#0000ff"],
        memory:["16GB","32GB","64GB"],
        images:["img/huawei/camera.jpg","img/huawei/battery.jpg","img/huawei/processor.jpg"],
        thumb:["img/huawei/9n/thumb1.jpg","img/huawei/9n/thumb2.jpg","img/huawei/9n/thumb3.jpg","img/huawei/9n/thumb4.jpg"],
        thumb_target:["img/huawei/9n/img-target1.jpg","img/huawei/9n/img-target2.jpg","img/huawei/9n/img-target3.jpg","img/huawei/9n/img-target4.jpg"],
        battery:"Get more done with an Adaptive Battery that delivers 7 hours of use on just a 15-minute charge. It’s designed to learn your favorite apps and reduce power to the ones you rarely use.",
        camera:"Take flawless photos with Portrait Mode. Capture beautiful portraits that focus on your subject as the background fades into a blur. Free, unlimited storage with Google Photos.² Save all your photos and videos with free, unlimited storage at high quality with Google Photos. Keep everyone in focus. Motion Auto Focus will make sure the people and pets in your shot stay sharp as you snap away.",
        processor:"3 years of security and OS updates. Keep your phone protected against the latest threats and performing at its best.5 Keep your data protected. The custom-made Titan M security chip helps secure the operating system and your most sensitive data, like passwords.6 Keep more of what you love. Use the Quick Switch Adapter to transfer your messages, contacts and photos to your new device.",
        inCart: false,
        inWishlist:false,
        count: 0,
        total: 0,
        specification:{
          brand:"Huawei",
          model:"Honor 9lite",
          camera:"12MP+5MP dual rear camera | 20MP+2MP dual front camera",
          battery:"4000mAH lithium-ion battery",
          processor:"1.8GHz Qualcomm Snapdragon 636 processor, Adreno 509",
          os:"Annote6 Oreo v8.1 operating system ",
          sf:"4GB RAM | 64GB internal memory expandable up to 256GB | Dual SIM (micro+nano) dual-standby (4G+4G)",
        },
      },
      {
        id: 14,
        title: "Redmi 7A",
        img: "img/redmi-1.png",
        price: 1,
        company: "Xiaomi",
        color: ["Red","OceanBlue","Gold"],
        colorType:["#ff0000","#66ccff","#e6ac00"],
        memory:["16GB","32GB","64GB"],
        images:["img/xiaomi/camera.jpg","img/xiaomi/battery.jpg","img/xiaomi/processor.jpg"],
        thumb:["img/xiaomi/7a/thumb1.jpg","img/xiaomi/7a/thumb2.jpg","img/xiaomi/7a/thumb3.jpg","img/xiaomi/7a/thumb4.jpg"],
        thumb_target:["img/xiaomi/7a/img-target1.jpg","img/xiaomi/7a/img-target2.jpg","img/xiaomi/7a/img-target3.jpg","img/xiaomi/7a/img-target4.jpg"],
        battery:"Get more done with an Adaptive Battery that delivers 7 hours of use on just a 15-minute charge. It’s designed to learn your favorite apps and reduce power to the ones you rarely use.",
        camera:"Take flawless photos with Portrait Mode. Capture beautiful portraits that focus on your subject as the background fades into a blur. Free, unlimited storage with Google Photos.² Save all your photos and videos with free, unlimited storage at high quality with Google Photos. Keep everyone in focus. Motion Auto Focus will make sure the people and pets in your shot stay sharp as you snap away.",
        processor:"3 years of security and OS updates. Keep your phone protected against the latest threats and performing at its best.5 Keep your data protected. The custom-made Titan M security chip helps secure the operating system and your most sensitive data, like passwords.6 Keep more of what you love. Use the Quick Switch Adapter to transfer your messages, contacts and photos to your new device.",
        inCart: false,
        inWishlist:false,
        count: 0,
        total: 0,
        specification:{
          brand:"Xiaomi",
          model:"Redmi 7A",
          camera:"12MP+5MP dual rear camera | 20MP+2MP dual front camera",
          battery:"4000mAH lithium-ion battery",
          processor:"1.8GHz Qualcomm Snapdragon 636 processor, Adreno 509",
          os:"Annote6 Oreo v8.1 operating system ",
          sf:"4GB RAM | 64GB internal memory expandable up to 256GB | Dual SIM (micro+nano) dual-standby (4G+4G)",
        },
      },
      {
        id: 15,
        title: "Nokia 7.1",
        img: "img/nokia-4.png",
        price: 1.5,
        company: "Nokia",
        color: ["Black","NavyBlue"],
        colorType:["#000000","#00004d"],
        memory:["16GB","32GB","64GB"],
        images:["img/nokia/camera.jpg","img/nokia/battery.jpg","img/nokia/processor.jpg"],
        thumb:["img/nokia/7.1/thumb1.jpg","img/nokia/7.1/thumb2.jpg","img/nokia/7.1/thumb3.jpg","img/nokia/7.1/thumb4.jpg"],
        thumb_target:["img/nokia/7.1/img-target1.jpg","img/nokia/7.1/img-target2.jpg","img/nokia/7.1/img-target3.jpg","img/nokia/7.1/img-target4.jpg"],
        battery:"Get more done with an Adaptive Battery that delivers 7 hours of use on just a 15-minute charge. It’s designed to learn your favorite apps and reduce power to the ones you rarely use.",
        camera:"Take flawless photos with Portrait Mode. Capture beautiful portraits that focus on your subject as the background fades into a blur. Free, unlimited storage with Google Photos.² Save all your photos and videos with free, unlimited storage at high quality with Google Photos. Keep everyone in focus. Motion Auto Focus will make sure the people and pets in your shot stay sharp as you snap away.",
        processor:"3 years of security and OS updates. Keep your phone protected against the latest threats and performing at its best.5 Keep your data protected. The custom-made Titan M security chip helps secure the operating system and your most sensitive data, like passwords.6 Keep more of what you love. Use the Quick Switch Adapter to transfer your messages, contacts and photos to your new device.",
        inCart: false,
        inWishlist:false,
        count: 0,
        total: 0,
        specification:{
          brand:"Nokia",
          model:"Nokia 7.1",
          camera:"16MP rear camera | 8MP front camera",
          battery:"3000mAH lithium-ion battery providing talk-time of 20 hours and standby time of 648 hours",
          processor:"1.3GHz Qualcomm Snapdragon 630 octa core processor",
          os:"Android v8.0 Oreo operating system ",
          sf:"4GB RAM | 64GB internal memory expandable up to 256GB | Dual SIM (micro+nano) dual-standby (4G+4G)",
        },
      },
      {
        id: 16,
        title: "Nokia 6.1",
        img: "img/nokia-5.jpg",
        price: 2.5,
        company: "Nokia",
        color: ["Black","NavyBlue"],
        colorType:["#000000","#00004d"],
        memory:["16GB","32GB","64GB"],
        images:["img/nokia/camera.jpg","img/nokia/battery.jpg","img/nokia/processor.jpg"],
        thumb:["img/nokia/6.1/thumb1.jpg","img/nokia/6.1/thumb2.jpg","img/nokia/6.1/thumb3.jpg","img/nokia/6.1/thumb4.jpg"],
        thumb_target:["img/nokia/6.1/img-target1.jpg","img/nokia/6.1/img-target2.jpg","img/nokia/6.1/img-target3.jpg","img/nokia/6.1/img-target4.jpg"],
        battery:"Get more done with an Adaptive Battery that delivers 7 hours of use on just a 15-minute charge. It’s designed to learn your favorite apps and reduce power to the ones you rarely use.",
        camera:"Take flawless photos with Portrait Mode. Capture beautiful portraits that focus on your subject as the background fades into a blur. Free, unlimited storage with Google Photos.² Save all your photos and videos with free, unlimited storage at high quality with Google Photos. Keep everyone in focus. Motion Auto Focus will make sure the people and pets in your shot stay sharp as you snap away.",
        processor:"3 years of security and OS updates. Keep your phone protected against the latest threats and performing at its best.5 Keep your data protected. The custom-made Titan M security chip helps secure the operating system and your most sensitive data, like passwords.6 Keep more of what you love. Use the Quick Switch Adapter to transfer your messages, contacts and photos to your new device.",
        inCart: false,
        inWishlist:false,
        count: 0,
        total: 0,
        specification:{
          brand:"Nokia",
          model:"Nokia 7.1",
          camera:"16MP rear camera | 8MP front camera",
          battery:"3000mAH lithium-ion battery providing talk-time of 20 hours and standby time of 648 hours",
          processor:"1.3GHz Qualcomm Snapdragon 630 octa core processor",
          os:"Android v8.0 Oreo operating system ",
          sf:"4GB RAM | 64GB internal memory expandable up to 256GB | Dual SIM (micro+nano) dual-standby (4G+4G)",
        },
      },
      {
        id: 17,
        title: "Google Pixel 3",
        img: "img/pixel-1.png",
        price: 3.5,
        company: "Google",
        color: ["Black","Pink","Grey"],
        colorType:["#000000","#ffe6e6","#78797E"],
        memory:["16GB","32GB","64GB"],
        images:["img/google/camera.jpg","img/google/battery.jpg","img/google/processor.jpg"],
        thumb:["img/google/3a/thumb1.jpg","img/google/3a/thumb2.jpg","img/google/3a/thumb3.jpg","img/google/3a/thumb4.jpg"],
        thumb_target:["img/google/3a/img-target1.jpg","img/google/3a/img-target2.jpg","img/google/3a/img-target3.jpg","img/google/3a/img-target4.jpg"],
        battery:"Get more done with an Adaptive Battery that delivers 7 hours of use on just a 15-minute charge. It’s designed to learn your favorite apps and reduce power to the ones you rarely use.",
        camera:"Take flawless photos with Portrait Mode. Capture beautiful portraits that focus on your subject as the background fades into a blur. Free, unlimited storage with Google Photos.² Save all your photos and videos with free, unlimited storage at high quality with Google Photos. Keep everyone in focus. Motion Auto Focus will make sure the people and pets in your shot stay sharp as you snap away.",
        processor:"3 years of security and OS updates. Keep your phone protected against the latest threats and performing at its best.5 Keep your data protected. The custom-made Titan M security chip helps secure the operating system and your most sensitive data, like passwords.6 Keep more of what you love. Use the Quick Switch Adapter to transfer your messages, contacts and photos to your new device.",
        inCart: false,
        inWishlist:false,
        count: 0,
        total: 0,
        specification:{
          brand:"Google",
          model:"Google Pixel 3",
          camera:"12.2MP primary camera and 8MP front facing camera",
          battery:"3520mAH lithium-ion battery",
          processor:"Qualcomm Snapdragon 845 64-bit octa core processor",
          os:"Android v9 Pie operating system with 2.5GHz",
          sf:"Single SIM, Music Player, Video Player, E-mail"
        },
      },
      {
        id: 18,
        title: " Google Pixel 2XL",
        img: "img/pixel-2.jpg",
        price: 4,
        company: "Google",
        color: ["Black","Blue","Grey","White"],
        colorType:["#000000","#0B1888","#78797E","#ffffff"],
        memory:["16GB","32GB","64GB"],
        images:["img/google/camera.jpg","img/google/battery.jpg","img/google/processor.jpg"],
        thumb:["img/google/xl/thumb1.jpg","img/google/xl/thumb2.jpg","img/google/xl/thumb3.jpg","img/google/xl/thumb4.jpg"],
        thumb_target:["img/google/xl/img-target1.jpg","img/google/xl/img-target2.jpg","img/google/xl/img-target3.jpg","img/google/xl/img-target4.jpg"],
        battery:"Get more done with an Adaptive Battery that delivers 7 hours of use on just a 15-minute charge. It’s designed to learn your favorite apps and reduce power to the ones you rarely use.",
        camera:"Take flawless photos with Portrait Mode. Capture beautiful portraits that focus on your subject as the background fades into a blur. Free, unlimited storage with Google Photos.² Save all your photos and videos with free, unlimited storage at high quality with Google Photos. Keep everyone in focus. Motion Auto Focus will make sure the people and pets in your shot stay sharp as you snap away.",
        processor:"3 years of security and OS updates. Keep your phone protected against the latest threats and performing at its best.5 Keep your data protected. The custom-made Titan M security chip helps secure the operating system and your most sensitive data, like passwords.6 Keep more of what you love. Use the Quick Switch Adapter to transfer your messages, contacts and photos to your new device.",
        inCart: false,
        inWishlist:false,
        count: 0,
        total: 0,
        specification:{
          brand:"Google",
          model:"Google Pixel 2XL",
          camera:"12.2MP primary camera and 8MP front facing camera",
          battery:"3520mAH lithium-ion battery",
          processor:"Snapdragon 845 64-bit octa core processor",
          os:"Android v9 Pie operating system with 2.5GHz",
          sf:"SIM: 4GB RAM | 64GB internal memory expandable up to 64GB | Single SIM, Music Player, Video Player, E-mail"
        },
      },
      {
        id: 19,
        title: "Samsung Galaxy A70",
        img: "img/samsung-1.png",
        price: 2.5,
        company: "Samsung",
        color: ["Black","Blue","Silver"],
        colorType:["#000000","#0B1888","#d9d9d9"],
        memory:["16GB","32GB","64GB"],
        images:["img/samsung/camera.jpg","img/samsung/battery.jpg","img/samsung/processor.jpg"],
        thumb:["img/samsung/a70/thumb1.jpg","img/samsung/a70/thumb2.jpg","img/samsung/a70/thumb3.jpg","img/samsung/a70/thumb4.jpg"],
        thumb_target:["img/samsung/a70/img-target1.jpg","img/samsung/a70/img-target2.jpg","img/samsung/a70/img-target3.jpg","img/samsung/a70/img-target4.jpg"],
        battery:"Get more done with an Adaptive Battery that delivers 7 hours of use on just a 15-minute charge. It’s designed to learn your favorite apps and reduce power to the ones you rarely use.",
        camera:"Take flawless photos with Portrait Mode. Capture beautiful portraits that focus on your subject as the background fades into a blur. Free, unlimited storage with Google Photos.² Save all your photos and videos with free, unlimited storage at high quality with Google Photos. Keep everyone in focus. Motion Auto Focus will make sure the people and pets in your shot stay sharp as you snap away.",
        processor:"3 years of security and OS updates. Keep your phone protected against the latest threats and performing at its best.5 Keep your data protected. The custom-made Titan M security chip helps secure the operating system and your most sensitive data, like passwords.6 Keep more of what you love. Use the Quick Switch Adapter to transfer your messages, contacts and photos to your new device.",
        inCart: false,
        inWishlist:false,
        count: 0,
        total: 0,
        specification:{
          brand:"Samsung",
          model:"Samsung Galaxy A70",
          camera:"32MP+8MP+5MP triple rear camera with f1.9, f2.2 wide angle and f2.2 with flash | 32MP front camera with f2.0",
          battery:"4500mAH lithium-ion battery with type-c fast charging | 25W charger in the box",
          processor:"2GHz + 1.7GHz Qualcomm Snapdragon SDM675 octa core processor",
          os:"Android Pie v9.0 operating system",
          sf:"Dual SIM (nano+nano) dual-standby (4G+4G), USB Version: USB 2.0 ; Color Depth (Main Display): 16M ; Bluetooth: v5.0"
        },
      },
      {
        id: 20,
        title: "Samsung Salaxy A80",
        img: "img/samsung-2.png",
        price: 3.5,
        company: "Samsung",
        color: ["Black","Blue","Silver"],
        colorType:["#000000","#0B1888","#d9d9d9"],
        memory:["16GB","32GB","64GB"],
        images:["img/samsung/camera.jpg","img/samsung/battery.jpg","img/samsung/processor.jpg"],
        thumb:["img/samsung/a80/thumb1.jpg","img/samsung/a80/thumb2.jpg","img/samsung/a80/thumb3.jpg","img/samsung/a80/thumb4.jpg"],
        thumb_target:["img/samsung/a80/img-target1.jpg","img/samsung/a80/img-target2.jpg","img/samsung/a80/img-target3.jpg","img/samsung/a80/img-target4.jpg"],
        battery:"Get more done with an Adaptive Battery that delivers 7 hours of use on just a 15-minute charge. It’s designed to learn your favorite apps and reduce power to the ones you rarely use.",
        camera:"Take flawless photos with Portrait Mode. Capture beautiful portraits that focus on your subject as the background fades into a blur. Free, unlimited storage with Google Photos.² Save all your photos and videos with free, unlimited storage at high quality with Google Photos. Keep everyone in focus. Motion Auto Focus will make sure the people and pets in your shot stay sharp as you snap away.",
        processor:"3 years of security and OS updates. Keep your phone protected against the latest threats and performing at its best.5 Keep your data protected. The custom-made Titan M security chip helps secure the operating system and your most sensitive data, like passwords.6 Keep more of what you love. Use the Quick Switch Adapter to transfer your messages, contacts and photos to your new device.",
        inCart: false,
        inWishlist:false,
        count: 0,
        total: 0,
        specification:{
          brand:"Samsung",
          model:"Samsung Galaxy A80",
          camera:"32MP+8MP+5MP triple rear camera with f1.9, f2.2 wide angle and f2.2 with flash | 32MP front camera with f2.0",
          battery:"4500mAH lithium-ion battery with type-c fast charging | 25W charger in the box",
          processor:"2GHz + 1.7GHz Qualcomm Snapdragon SDM675 octa core processor",
          os:"Android Pie v9.0 operating system",
          sf:"Dual SIM (nano+nano) dual-standby (4G+4G), USB Version: USB 2.0 ; Color Depth (Main Display): 16M ; Bluetooth: v5.0"
        },
      },
      {
        id: 21,
        title: "Samsung Galaxy S10 Plus",
        img: "img/samsung-3.png",
        price: 2.5,
        company: "Samsung",
        color: ["Black","Blue","Silver"],
        colorType:["#000000","#0B1888","#d9d9d9"],
        memory:["16GB","32GB","64GB"],
        images:["img/samsung/camera.jpg","img/samsung/battery.jpg","img/samsung/processor.jpg"],
        thumb:["img/samsung/s10/thumb1.jpg","img/samsung/s10/thumb2.jpg","img/samsung/s10/thumb3.jpg","img/samsung/s10/thumb4.jpg"],
        thumb_target:["img/samsung/s10/img-target1.jpg","img/samsung/s10/img-target2.jpg","img/samsung/s10/img-target3.jpg","img/samsung/s10/img-target4.jpg"],
        battery:"Get more done with an Adaptive Battery that delivers 7 hours of use on just a 15-minute charge. It’s designed to learn your favorite apps and reduce power to the ones you rarely use.",
        camera:"Take flawless photos with Portrait Mode. Capture beautiful portraits that focus on your subject as the background fades into a blur. Free, unlimited storage with Google Photos.² Save all your photos and videos with free, unlimited storage at high quality with Google Photos. Keep everyone in focus. Motion Auto Focus will make sure the people and pets in your shot stay sharp as you snap away.",
        processor:"3 years of security and OS updates. Keep your phone protected against the latest threats and performing at its best.5 Keep your data protected. The custom-made Titan M security chip helps secure the operating system and your most sensitive data, like passwords.6 Keep more of what you love. Use the Quick Switch Adapter to transfer your messages, contacts and photos to your new device.",
        inCart: false,
        inWishlist:false,
        count: 0,
        total: 0,
        specification:{
          brand:"Samsung",
          model:"Samsung Galaxy S10 Plus",
          camera:"32MP+8MP+5MP triple rear camera with f1.9, f2.2 wide angle and f2.2 with flash | 32MP front camera with f2.0",
          battery:"4500mAH lithium-ion battery with type-c fast charging | 25W charger in the box",
          processor:"2GHz + 1.7GHz Qualcomm Snapdragon SDM675 octa core processor",
          os:"Android Pie v9.0 operating system",
          sf:"Dual SIM (nano+nano) dual-standby (4G+4G), USB Version: USB 2.0 ; Color Depth (Main Display): 16M ; Bluetooth: v5.0"
        },
      },
      {
        id: 22,
        title: "Sony Xperia",
        img: "img/sony-1.png",
        price: 2.6,
        company: "Sony",
        color: ["Black","NavyBlue"],
        colorType:["#000000","#00004d"],
        memory:["16GB","32GB","64GB"],
        images:["img/sony/camera.jpg","img/sony/battery.jpg","img/sony/processor.jpg"],
        thumb:["img/sony/thumb1.jpg","img/sony/thumb2.jpg","img/sony/thumb3.jpg","img/sony/thumb4.jpg"],
        thumb_target:["img/sony/img-target1.jpg","img/sony/img-target2.jpg","img/sony/img-target3.jpg","img/sony/img-target4.jpg"],
        battery:"Get more done with an Adaptive Battery that delivers 7 hours of use on just a 15-minute charge. It’s designed to learn your favorite apps and reduce power to the ones you rarely use.",
        camera:"Take flawless photos with Portrait Mode. Capture beautiful portraits that focus on your subject as the background fades into a blur. Free, unlimited storage with Google Photos.² Save all your photos and videos with free, unlimited storage at high quality with Google Photos. Keep everyone in focus. Motion Auto Focus will make sure the people and pets in your shot stay sharp as you snap away.",
        processor:"3 years of security and OS updates. Keep your phone protected against the latest threats and performing at its best.5 Keep your data protected. The custom-made Titan M security chip helps secure the operating system and your most sensitive data, like passwords.6 Keep more of what you love. Use the Quick Switch Adapter to transfer your messages, contacts and photos to your new device.",
        inCart: false,
        inWishlist:false,
        count: 0,
        total: 0,
        specification:{
          brand:"Sony",
          model:"Sony Xperia",
          camera:"16MP rear camera | 8MP front camera",
          battery:"3000mAH lithium-ion battery providing talk-time of 20 hours and standby time of 648 hours",
          processor:"1.3GHz Qualcomm Snapdragon 630 octa core processor",
          os:"Android v8.0 Oreo operating system ",
          sf:"4GB RAM | 64GB internal memory expandable up to 256GB | Dual SIM (micro+nano) dual-standby (4G+4G)",
        },
      },
      {
        id: 23,
        title: " Google Pixel 3a XL",
        img: "img/pixel-3.png",
        price: 2.8,
        company: "Google",
        color: ["Black","Blue","Grey"],
        colorType:["#000000","#0B1888","#78797E"],
        memory:["16GB","32GB","64GB"],
        images:["img/google/camera.jpg","img/google/battery.jpg","img/google/processor.jpg"],
        thumb:["img/google/thumb1.jpg","img/google/thumb2.jpg","img/google/thumb3.jpg","img/google/thumb4.jpg"],
        thumb_target:["img/google/img-target1.jpg","img/google/img-target2.jpg","img/google/img-target3.jpg","img/google/img-target4.jpg"],
        battery:"Get more done with an Adaptive Battery that delivers 7 hours of use on just a 15-minute charge. It’s designed to learn your favorite apps and reduce power to the ones you rarely use.",
        camera:"Take flawless photos with Portrait Mode. Capture beautiful portraits that focus on your subject as the background fades into a blur. Free, unlimited storage with Google Photos.² Save all your photos and videos with free, unlimited storage at high quality with Google Photos. Keep everyone in focus. Motion Auto Focus will make sure the people and pets in your shot stay sharp as you snap away.",
        processor:"3 years of security and OS updates. Keep your phone protected against the latest threats and performing at its best.5 Keep your data protected. The custom-made Titan M security chip helps secure the operating system and your most sensitive data, like passwords.6 Keep more of what you love. Use the Quick Switch Adapter to transfer your messages, contacts and photos to your new device.",
        inCart: false,
        inWishlist:false,
        count: 0,
        total: 0,
        specification:{
          brand:"Google",
          model:"Google Pixel",
          camera:"12.2MP primary camera and 8MP front facing camera",
          battery:"3520mAH lithium-ion battery",
          processor:"Snapdragon 835 64-bit octa core processor",
          os:"Android v8.0.1 Oreo operating system",
          sf:"Single SIM, Music Player, Video Player, E-mail"
        },
      },
      {
        id: 24,
        title: " Google Pixel 3XL",
        img: "img/pixel-4.png",
        price: 2.5,
        company: "Google",
        color: ["Black","Blue","Grey"],
        colorType:["#000000","#0B1888","#78797E"],
        memory:["16GB","32GB","64GB"],
        images:["img/google/camera.jpg","img/google/battery.jpg","img/google/processor.jpg"],
        thumb:["img/google/xl/thumb1.jpg","img/google/xl/thumb2.jpg","img/google/xl/thumb3.jpg","img/google/xl/thumb4.jpg"],
        thumb_target:["img/google/xl/img-target1.jpg","img/google/xl/img-target2.jpg","img/google/xl/img-target3.jpg","img/google/xl/img-target4.jpg"],
        battery:"Get more done with an Adaptive Battery that delivers 7 hours of use on just a 15-minute charge. It’s designed to learn your favorite apps and reduce power to the ones you rarely use.",
        camera:"Take flawless photos with Portrait Mode. Capture beautiful portraits that focus on your subject as the background fades into a blur. Free, unlimited storage with Google Photos.² Save all your photos and videos with free, unlimited storage at high quality with Google Photos. Keep everyone in focus. Motion Auto Focus will make sure the people and pets in your shot stay sharp as you snap away.",
        processor:"3 years of security and OS updates. Keep your phone protected against the latest threats and performing at its best.5 Keep your data protected. The custom-made Titan M security chip helps secure the operating system and your most sensitive data, like passwords.6 Keep more of what you love. Use the Quick Switch Adapter to transfer your messages, contacts and photos to your new device.",
        inCart: false,
        inWishlist:false,
        count: 0,
        total: 0,
        specification:{
          brand:"Google",
          model:"Google Pixel 3XL",
          camera:"12.2MP primary camera and 8MP front facing camera",
          battery:"3520mAH lithium-ion battery",
          processor:"Snapdragon 835 64-bit octa core processor",
          os:"Android v8.0.1 Oreo operating system",
          sf:"Single SIM, Music Player, Video Player, E-mail"
        },
      }

  ];
  
  export const detailProduct = {
    id: 1,
    title: "Google Pixel - Black",
    img: "img/product-1.png",
    price: 10,
    color: ["black","blue","grey"],
    colorType:["#000000","#0B1888","#78797E"],
    memory:["16GB","32GB","64GB"],
    company: "google",
    images:["img/google/camera.jpg","img/google/battery.jpg","img/google/processor.jpg"],
    thumb:["img/google/thumb1.jpg","img/google/thumb2.jpg","img/google/thumb3.jpg","img/google/thumb4.jpg"],
    thumb_target:["img/google/img-target1.jpg","img/google/img-target2.jpg","img/google/img-target3.jpg","img/google/img-target4.jpg"],
    battery:"Get more done with an Adaptive Battery that delivers 7 hours of use on just a 15-minute charge. It’s designed to learn your favorite apps and reduce power to the ones you rarely use.",
    camera:"Take flawless photos with Portrait Mode. Capture beautiful portraits that focus on your subject as the background fades into a blur. Free, unlimited storage with Google Photos.² Save all your photos and videos with free, unlimited storage at high quality with Google Photos. Keep everyone in focus. Motion Auto Focus will make sure the people and pets in your shot stay sharp as you snap away.",
    processor:"3 years of security and OS updates. Keep your phone protected against the latest threats and performing at its best.5 Keep your data protected. The custom-made Titan M security chip helps secure the operating system and your most sensitive data, like passwords.6 Keep more of what you love. Use the Quick Switch Adapter to transfer your messages, contacts and photos to your new device.",
    inCart: false,
    inWishlist:false,
    count: 0,
    total: 0,
    specification:{
      brand:"Google",
      model:"Google Pixel",
      camera:"12.2MP primary camera and 8MP front facing camera",
      battery:"3520mAH lithium-ion battery",
      processor:"Snapdragon 835 64-bit octa core processor",
      os:"Android v8.0.1 Oreo operating system",
      sf:"Single SIM, Music Player, Video Player, E-mail"
    },
  };